on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build --argstr system armv7l-linux .#default
    - uses: actions/upload-artifact@v3
      with:
        name: static-build
        path: result/bin
